[tool.poetry]
name = "interpolation"
version = "2.2.3"
readme = "README.md"
description = "Interpolation in Python"
authors = [
    "Pablo Winant <pablo.winant@gmail.com>",
    "Chase Coleman <cc7768@gmail.com>",
    "Spencer Lyon <spencerlyon2@gmail.com>"
]
maintainers = [
    "Pablo Winant <pablo.winant@gmail.com>"
]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
numba = ">=0.47"
numpy = "^1.18.1"
tempita = "^0.5.2"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mkdocs = "^1.1"
pymdown-extensions = "^7.1"
python-markdown-math = "^0.6"
mypy = "^0.782"
black = "^22.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
